// DO NOT EDIT: This file is autogenerated via the builtin command.

package s3

import (
	flux "github.com/influxdata/flux"
	ast "github.com/influxdata/flux/ast"
)

func init() {
	flux.RegisterPackage(pkgAST)
}

var pkgAST = &ast.Package{
	BaseNode: ast.BaseNode{
		Errors: nil,
		Loc:    nil,
	},
	Files: []*ast.File{&ast.File{
		BaseNode: ast.BaseNode{
			Errors: nil,
			Loc: &ast.SourceLocation{
				End: ast.Position{
					Column: 2,
					Line:   7,
				},
				File:   "s3.flux",
				Source: "package s3\n\nbuiltin openFile\n\ns3 = {\n  openFile:openFile,\n}",
				Start: ast.Position{
					Column: 1,
					Line:   1,
				},
			},
		},
		Body: []ast.Statement{&ast.BuiltinStatement{
			BaseNode: ast.BaseNode{
				Errors: nil,
				Loc: &ast.SourceLocation{
					End: ast.Position{
						Column: 17,
						Line:   3,
					},
					File:   "s3.flux",
					Source: "builtin openFile",
					Start: ast.Position{
						Column: 1,
						Line:   3,
					},
				},
			},
			ID: &ast.Identifier{
				BaseNode: ast.BaseNode{
					Errors: nil,
					Loc: &ast.SourceLocation{
						End: ast.Position{
							Column: 17,
							Line:   3,
						},
						File:   "s3.flux",
						Source: "openFile",
						Start: ast.Position{
							Column: 9,
							Line:   3,
						},
					},
				},
				Name: "openFile",
			},
		}, &ast.VariableAssignment{
			BaseNode: ast.BaseNode{
				Errors: nil,
				Loc: &ast.SourceLocation{
					End: ast.Position{
						Column: 2,
						Line:   7,
					},
					File:   "s3.flux",
					Source: "s3 = {\n  openFile:openFile,\n}",
					Start: ast.Position{
						Column: 1,
						Line:   5,
					},
				},
			},
			ID: &ast.Identifier{
				BaseNode: ast.BaseNode{
					Errors: nil,
					Loc: &ast.SourceLocation{
						End: ast.Position{
							Column: 3,
							Line:   5,
						},
						File:   "s3.flux",
						Source: "s3",
						Start: ast.Position{
							Column: 1,
							Line:   5,
						},
					},
				},
				Name: "s3",
			},
			Init: &ast.ObjectExpression{
				BaseNode: ast.BaseNode{
					Errors: nil,
					Loc: &ast.SourceLocation{
						End: ast.Position{
							Column: 2,
							Line:   7,
						},
						File:   "s3.flux",
						Source: "{\n  openFile:openFile,\n}",
						Start: ast.Position{
							Column: 6,
							Line:   5,
						},
					},
				},
				Properties: []*ast.Property{&ast.Property{
					BaseNode: ast.BaseNode{
						Errors: nil,
						Loc: &ast.SourceLocation{
							End: ast.Position{
								Column: 20,
								Line:   6,
							},
							File:   "s3.flux",
							Source: "openFile:openFile",
							Start: ast.Position{
								Column: 3,
								Line:   6,
							},
						},
					},
					Key: &ast.Identifier{
						BaseNode: ast.BaseNode{
							Errors: nil,
							Loc: &ast.SourceLocation{
								End: ast.Position{
									Column: 11,
									Line:   6,
								},
								File:   "s3.flux",
								Source: "openFile",
								Start: ast.Position{
									Column: 3,
									Line:   6,
								},
							},
						},
						Name: "openFile",
					},
					Value: &ast.Identifier{
						BaseNode: ast.BaseNode{
							Errors: nil,
							Loc: &ast.SourceLocation{
								End: ast.Position{
									Column: 20,
									Line:   6,
								},
								File:   "s3.flux",
								Source: "openFile",
								Start: ast.Position{
									Column: 12,
									Line:   6,
								},
							},
						},
						Name: "openFile",
					},
				}},
				With: nil,
			},
		}},
		Imports: nil,
		Name:    "s3.flux",
		Package: &ast.PackageClause{
			BaseNode: ast.BaseNode{
				Errors: nil,
				Loc: &ast.SourceLocation{
					End: ast.Position{
						Column: 11,
						Line:   1,
					},
					File:   "s3.flux",
					Source: "package s3",
					Start: ast.Position{
						Column: 1,
						Line:   1,
					},
				},
			},
			Name: &ast.Identifier{
				BaseNode: ast.BaseNode{
					Errors: nil,
					Loc: &ast.SourceLocation{
						End: ast.Position{
							Column: 11,
							Line:   1,
						},
						File:   "s3.flux",
						Source: "s3",
						Start: ast.Position{
							Column: 9,
							Line:   1,
						},
					},
				},
				Name: "s3",
			},
		},
	}},
	Package: "s3",
	Path:    "s3",
}
